copyfiles:
	cp $(filepath) .

compile-timsort:
	@echo 'Python solution. Nothing to compile.'

run-timsort:
	python3 angular-sort.py $(input) $(output-sorted) $(output-info)

list-timsort:
	ls timsort.py

show-timsort:
	@echo 'Showing python file timsort.py'
	cat timsort.py

compile-closest:
	@echo 'Python solution. Nothing to compile.'

run-closest:
	python3 closest.py $(points) $(output)

list-closest:
	ls closestt.py

show-closest:
	cat closest.py 
