copyfiles:
	cp $(filepath) .

compile:
	@echo 'Python solution. Nothing to compile.'

run:
	python3 search.py

list:
	ls *.py

show:
	@echo 'Showing python files search.py and utility.py'
	cat search.py
	cat utility.py
